/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Adrian
 */
public class ControlAsistencia extends javax.swing.JFrame {
    
    /**
     * Creates new form MainFrame
     */
    public ControlAsistencia() {
        initComponents();
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jLabeNombre = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        btnConsultarEventos = new javax.swing.JMenuItem();
        btnControlarRegistro = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        btnConsultarParticipantes = new javax.swing.JMenuItem();
        btnRegistrarUsuario = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        btnEditarInformacion = new javax.swing.JMenuItem();

        jMenuItem7.setText("jMenuItem7");

        jMenuItem8.setText("jMenuItem8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabeNombre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabeNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeNombre.setText("Bienvenido");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Registre su huella dactilar para habilitar su acceso al evento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(290, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Selecciona el evento");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Evento 1", "Evento 2", "Evento 3", "Evento 4" }));

        jMenu2.setLabel("Eventos");

        btnConsultarEventos.setText("Consultar");
        btnConsultarEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarEventosActionPerformed(evt);
            }
        });
        jMenu2.add(btnConsultarEventos);

        btnControlarRegistro.setText("Control registro");
        btnControlarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControlarRegistroActionPerformed(evt);
            }
        });
        jMenu2.add(btnControlarRegistro);

        jMenuBar1.add(jMenu2);

        jMenu1.setLabel("Participantes");

        btnConsultarParticipantes.setText("Consultar");
        btnConsultarParticipantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarParticipantesActionPerformed(evt);
            }
        });
        jMenu1.add(btnConsultarParticipantes);

        btnRegistrarUsuario.setText("Registrar");
        btnRegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(btnRegistrarUsuario);

        jMenuBar1.add(jMenu1);

        jMenu3.setLabel("Configuraciones");

        btnEditarInformacion.setText("Editar Informacion");
        btnEditarInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarInformacionActionPerformed(evt);
            }
        });
        jMenu3.add(btnEditarInformacion);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabeNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabeNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jLabeNombre.getAccessibleContext().setAccessibleName("Bienvenido ");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarParticipantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarParticipantesActionPerformed
        // TODO add your handling code here:
        Usuarios jFrameUsuarios=new Usuarios();
        jFrameUsuarios.setVisible(true);
        jFrameUsuarios.jLabeNombre.setText("");
        jFrameUsuarios.jLabeNombre.setText(this.jLabeNombre.getText());
        dispose();
    }//GEN-LAST:event_btnConsultarParticipantesActionPerformed

    private void btnConsultarEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarEventosActionPerformed
        // TODO add your handling code here:
        
        Eventos jFrameEventos=new Eventos();
        jFrameEventos.setVisible(true);
        jFrameEventos.jLabeNombre.setText("");
        jFrameEventos.jLabeNombre.setText(this.jLabeNombre.getText());
        dispose();
        
        
    }//GEN-LAST:event_btnConsultarEventosActionPerformed

    private void btnRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarUsuarioActionPerformed
        // TODO add your handling code here:
       RegistroUsuarios jFrameUsuarios=new RegistroUsuarios();
        jFrameUsuarios.setVisible(true);
        jFrameUsuarios.jLabeNombre.setText("");
        jFrameUsuarios.jLabeNombre.setText(this.jLabeNombre.getText());
        dispose();
    }//GEN-LAST:event_btnRegistrarUsuarioActionPerformed

    private void btnEditarInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarInformacionActionPerformed
        // TODO add your handling code here:
        Configuracion jFrameConfiguracion=new Configuracion();
        jFrameConfiguracion.setVisible(true);
        jFrameConfiguracion.jLabeNombre.setText("");
        jFrameConfiguracion.jLabeNombre.setText(this.jLabeNombre.getText());
        dispose();
    }//GEN-LAST:event_btnEditarInformacionActionPerformed

    private void btnControlarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlarRegistroActionPerformed
        // TODO add your handling code here:
           ControlAsistencia jFrameAsistencia=new ControlAsistencia();
            jFrameAsistencia.setVisible(true);
            jFrameAsistencia.jLabeNombre.setText("");
            jFrameAsistencia.jLabeNombre.setText(this.jLabeNombre.getText());
            dispose();
    }//GEN-LAST:event_btnControlarRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              
                new MainFrame().setVisible(true);
            }

            
        });
    }

   
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnConsultarEventos;
    private javax.swing.JMenuItem btnConsultarParticipantes;
    private javax.swing.JMenuItem btnControlarRegistro;
    private javax.swing.JMenuItem btnEditarInformacion;
    private javax.swing.JMenuItem btnRegistrarUsuario;
    private javax.swing.JComboBox<String> jComboBox1;
    public javax.swing.JLabel jLabeNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
